### ISSUE TITLE
[feat] 마이페이지 / 기능 구현 

### ISSUE THREAD

**Issue by leeeha** [LoveMarker/LoveMarker-Android#50]
##  📌 TODO
- [x] 커플 정보 조회 
- [x] 닉네임 변경 
- [ ] 내가 올린 추억 조회 
- [x] 커플 연결 해제 
- [ ] 로그아웃 / 회원탈퇴
