### ISSUE TITLE
[mod] 이전 화면에 따라 커플 매칭 네비게이션 변경 

### ISSUE THREAD

**Issue by leeeha** [LoveMarker/LoveMarker-Android#57]
## ✨ ISSUE 

이전 화면에 따라 초대 코드 생성 및 입력 후 네비게이션 변경 

##  📌 TODO
- [x] 로그인 -> 닉네임 -> 커플 매칭 -> 지도 화면 
- [x] 지도 또는 아카이빙 탭의 다이얼로그 -> 커플 매칭 -> 이전 화면 (커플 데이터스토어의 getCoupleConnectState 결과 반영) 
- [x] 마이페이지 -> 커플 매칭 -> 이전 화면 (getMyPageInfo 함수 호출해서 서버 데이터 반영) 
- [x] 이전 화면에도 최신 커플 상태 반영
